# Generated by Django 3.0.5 on 2020-04-01 21:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(auto_now=True, verbose_name='Data de upload')),
                ('contact_infos', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
