# Generated by Django 3.0.5 on 2020-04-02 00:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Nome do modelo')),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='fields_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contato.ContactFields'),
        ),
    ]
