# Generated by Django 3.0.5 on 2020-04-02 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_auto_20200402_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='fields_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contato.ContactFields'),
            preserve_default=False,
        ),
    ]
