# Generated by Django 3.0.5 on 2020-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_auto_20200402_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='upload_date',
            field=models.DateField(auto_now_add=True, verbose_name='Data de upload'),
        ),
    ]
